// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC_MGXrd5WChtQd2CCEAI5mTAkwdu3Lh5o',
    appId: '1:286057917031:web:2e91ba7f5afd122756c2c2',
    messagingSenderId: '286057917031',
    projectId: 'tictactoe-77d25',
    authDomain: 'tictactoe-77d25.firebaseapp.com',
    storageBucket: 'tictactoe-77d25.appspot.com',
    measurementId: 'G-800GJYH816',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBrYlS4CzdChjAxl8gDEpHm4xNaRyu0w34',
    appId: '1:286057917031:android:e6de60ce95f1172c56c2c2',
    messagingSenderId: '286057917031',
    projectId: 'tictactoe-77d25',
    storageBucket: 'tictactoe-77d25.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBlhhU_PkcXWVWScni1IVcbGx_5eMxOiqc',
    appId: '1:286057917031:ios:fb36543942f181ce56c2c2',
    messagingSenderId: '286057917031',
    projectId: 'tictactoe-77d25',
    storageBucket: 'tictactoe-77d25.appspot.com',
    iosBundleId: 'com.example.ticTacToe',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBlhhU_PkcXWVWScni1IVcbGx_5eMxOiqc',
    appId: '1:286057917031:ios:fb36543942f181ce56c2c2',
    messagingSenderId: '286057917031',
    projectId: 'tictactoe-77d25',
    storageBucket: 'tictactoe-77d25.appspot.com',
    iosBundleId: 'com.example.ticTacToe',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC_MGXrd5WChtQd2CCEAI5mTAkwdu3Lh5o',
    appId: '1:286057917031:web:9d49a1b57e86ac4856c2c2',
    messagingSenderId: '286057917031',
    projectId: 'tictactoe-77d25',
    authDomain: 'tictactoe-77d25.firebaseapp.com',
    storageBucket: 'tictactoe-77d25.appspot.com',
    measurementId: 'G-8EDJQTGKDM',
  );
}
